version: '3'

services:
  nginx:
    image: nginx:1.20-alpine
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
    depends_on:
      - app
      - frontend

  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    expose:
      - 9000
    depends_on:
      - db
    entrypoint: /entrypoint.sh
    command: php-fpm

  frontend:
    build:
      context: .
      dockerfile: ./.docker/frontend/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: /entrypoint.sh
    ports:
      - 8080:8080
    command: npm run dev

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d

volumes:
  database-data:
